//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWebApiRentalCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_not_avalable
    {
        public int id { get; set; }
        public string producer { get; set; }
        public string model { get; set; }
        public int cost_per_day { get; set; }
        public int fainancial_penalty { get; set; }
        public System.DateTime production_year { get; set; }
        public string gear { get; set; }
        public string img { get; set; }
        public int car_number { get; set; }
        public string banking_adrress { get; set; }
        public int banking_longitude { get; set; }
        public string banking_name { get; set; }
    }
}
