//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWebApiRentalCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string img { get; set; }
    }
}
